# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GlacioTools
                                 A QGIS plugin
 This plugin facilitates data processing for glacier monitoring, including elevation difference, field interpolation, and GCP monographies.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-19
        copyright            : (C) 2024 by Sebastian Fajardo Turner
        email                : sfajardoturner97@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GlacioTools class from file GlacioTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .glaciotools import GlacioTools
    return GlacioTools(iface)
